import Head from 'next/head'
import { useContext } from "react";
import { GlobalContext } from "@utils/GlobalContext";
import { PrismaClient } from '@prisma/client';
import Image from 'next/image';
import Link from 'next/link';

export async function getServerSideProps() {
  const prisma = new PrismaClient();
  const artists = await prisma.artist.findMany({
    include: { songs: true }
  });

  return {
    props: {
      artists
    }
  };
}

export default function Home({ artists }) {
  const { darkMode, setDarkMode } = useContext(GlobalContext);

  return (
    <>
      <Head>
        <title>Artists</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen p-8 md:p-12">
        <div className="max-w-lg mx-auto">

          <nav className="flex justify-between mb-8 gap-x-4">
            <Link href="/">
              <span className="text-blue-500 hover:text-blue-600 font-medium transition-all hover:cursor-pointer">Songs</span>
            </Link>
            <Link href="/artists">
              <span className="text-blue-500 hover:text-blue-600 font-medium transition-all hover:cursor-pointer">Artists</span>
            </Link>
            <div onClick={() => setDarkMode(!darkMode)} className="transition-all cursor-pointer w-12 h-7 dark:bg-blue-500 bg-neutral-200 rounded-full relative">
              <div className="h-5 w-5 bg-white rounded-full absolute top-1 transition-all dark:left-6 left-1"></div>
            </div>
          </nav>

          <h1 className="text-neutral-700 dark:text-gray-100 text-2xl font-bold">Artist List</h1>

          <div className="mt-6 grid grid-cols-1 md:grid-cols-2 gap-4">
            {artists.map(artist =>
              <div key={artist.id} className="border dark:border-neutral-800 rounded my-2">
                <Link href={`artist/${artist.id}`}>
                  <div className="group">
                    <div className="transition duration-300 hover:cursor-pointer">
                      <div className="relative h-56 md:h-52">
                        <Image
                          alt={artist.name}
                          src={artist.coverUrl}
                          className="rounded"
                          layout='fill'
                        />
                      </div>
                      <div className="p-3 flex justify-between">
                        <div>
                          <h2 className="text-md sm:text-lg font-medium dark:text-white text-neutral-800 group-hover:text-blue-500 transition duration-300">{artist.name}</h2>
                          <p className="text-sm sm:text-base text-neutral-700 dark:text-gray-300 mt-1">{artist.genre}</p>
                        </div>
                        <div className="flex items-end">
                          <p className="text-sm  text-neutral-700 dark:text-gray-300">{artist.songs.length} song</p>
                        </div>
                      </div>
                    </div>
                  </div>
                </Link>
              </div>
            )}
          </div>

        </div>
      </main>
    </>
  )
}
